config/routes.rb
Rails.application.routes.draw do
#    namespace :activity do
#        resources :notes
#        resources :participants
#    end


    devise_for :users,
    controllers: {:registrations => "registrations"}

    
    as :user do
        get "/registrations", to: "registrations#index"
        get "/registrations/new", to: "registrations#new"
        post "/registrations", to: "registrations#create"

        
    end
    resources :activities do
        scope module: :activity do 
            resources :notes
            resources :participants
        end
        
        
    end
#    devise_for :users
#    resources :users_admin, :controller => 'users'
    get 'home/index'
    root to: "home#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
<div class="container-fluid">
  <a class="navbar-brand">Lomax Technologies</a>
  <% name = current_user.present? ? current_user.email : 'Guest' %>
          <% name2 = current_user.present? ? current_user.username : 'Guest' %>
          <p>You are logged as: <%= name %> 
          <!--<p>Welcome <%= name2 %> </p>-->
  <% name = current_user.present? ? current_user.first_name : 'Desconocido' %>
  <% current_user %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
      
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <% if can? :manage, @users %>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        <%end%>
        </li>
        <li class="nav-item">
          <%= link_to 'Actividades', activities_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', registrations_path, class: 'nav-link' %>
        </li>

      <% else %>

        <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>

      <% if activities_path%>
        <li class="nav-item">
          <%= link_to 'Home', home_index_path, class: 'nav-link' %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to 'Activities', activities_path, class: 'nav-link' %>
        </li>
      <% end %>

    </ul>
  </div>
</div>
</nav>