config/routes.rb
Rails.application.routes.draw do
#    namespace :activity do
#        resources :notes
#        resources :participants
#    end


    devise_for :users,
    controllers: {:registrations => "registrations"}

    
    as :user do
        get "/registrations", to: "registrations#index"
        get "/registrations/new", to: "registrations#new"
        post "/registrations", to: "registrations#create"

        
    end
    resources :activities do
        scope module: :activity do 
            resources :notes
            resources :participants
        end
        
        
    end
#    devise_for :users
#    resources :users_admin, :controller => 'users'
    get 'home/index'
    root to: "home#index"
end

app/models/activity.rb
class Activity < ApplicationRecord

    enum type_activity: {
        publico: "Publico", 
        privado: "Privado"    
      }

    has_many :activity_note, dependent: :delete_all, class_name: "Activity::Note", foreign_key: "activities_id"
    has_many :activity_participant, dependent: :delete_all, class_name: "Activity::Participant", foreign_key: "activities_id"
    belongs_to :user, class_name: "User", foreign_key: "users_id"
    validates :name, presence: true, allow_blank: false
    validates :description, presence: true, allow_blank: false
    validates :location, presence: true, allow_blank: false
    validates :total_cost, presence: true, allow_blank: false
    validates :initial_date, presence: true, allow_blank: false
    validates :end_date, presence: true, allow_blank: false
    validates :state, presence: true, allow_blank: false


end

app/models/activity/note.rb
class Activity::Note < ApplicationRecord
   belongs_to :user, foreign_key: 'users_id'
   belongs_to :activity, foreign_key: 'activities_id'

   validates :comment, presence: true, allow_blank: false
   
end

app/models/activity/participant.rb
class Activity::Participant < ApplicationRecord
    belongs_to :user, foreign_key: 'users_id'
    belongs_to :activity, foreign_key: 'activities_id'


    validates :user, uniqueness: { scope: :activity, message: 'Must be unique for the same activity'}
  

    validates :participation_type, presence: true, allow_blank: false
    validates :contribution, presence: true, allow_blank: false
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]
  
  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
 
  def destroy
    if can? :destroy, @activity
    @activity.destroy
      respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
      end
    else
      respond_to do |format|
      format.html { redirect_to activities_url, notice: " Your role is not high enough to do this, please contact your administrator." }
      format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.fetch(:activity, {}).permit(:name, :description, :location, :total_cost, :type_activity, :initial_date, :end_date, :state)
    end
end

app/controllers/activity/notes_controller.rb
class Activity::NotesController < ApplicationController
  before_action :set_activity_note, only: %i[ show edit update destroy ]

  # GET /activity/notes or /activity/notes.json
  def index
    @activity = Activity.find_by_id(params[:activity_id])
    @activity_notes = Activity::Note.where(activities_id: params[:activity_id]) 
  end

  # GET /activity/notes/1 or /activity/notes/1.json
  def show
    
  end

  # GET /activity/notes/new
  def new
    @activity_note = Activity::Note.new
  end

  # GET /activity/notes/1/edit
  def edit
  end

  # POST /activity/notes or /activity/notes.json
  def create
      

    @activity_note = Activity::Note.new(activity_note_params)
    @activity_note.user= current_user
    @activity_note.activity = Activity.find_by_id(params[:activity_id])

    respond_to do |format|
      if @activity_note.save
        format.html { redirect_to activity_notes_url(@activity_note.activity, @notes), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @activity_note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity/notes/1 or /activity/notes/1.json
  def update
    respond_to do |format|
      if @activity_note.update(activity_note_params)
        format.html { redirect_to activity_notes_url(@activity_note.activity, @notes), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @activity_note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity/notes/1 or /activity/notes/1.json
  def destroy
    @activity_note.destroy
    respond_to do |format|
      format.html { redirect_to activity_notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_note
      @activity_note = Activity::Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_note_params
      params.fetch(:activity_note, {}).permit(:comment)
    end
end

app/controllers/activity/participants_controller.rb
class Activity::ParticipantsController < ApplicationController
  before_action :set_activity_participant, only: %i[ show edit update destroy ]

  # GET /activity/participants or /activity/participants.json
  def index
    @activity = Activity.find_by_id(params[:activity_id])
    @activity_participants = Activity::Participant.where(activities_id: params[:activity_id]) 
    
  end

  # GET /activity/participants/1 or /activity/participants/1.json
  def show
  end

  # GET /activity/participants/new
  def new
    @activity_participant = Activity::Participant.new
  end

  # GET /activity/participants/1/edit
  def edit
  end

  # POST /activity/participants or /activity/participants.json
  def create
    @activity_participant = Activity::Participant.new(activity_participant_params)
    #@activity_participant.user = current_user
    @activity_participant.activity = Activity.find_by_id(params[:activity_id])

    respond_to do |format|
      if @activity_participant.save
        format.html { redirect_to activity_participants_url, notice: "Participant was successfully created." }
        format.json { render :show, status: :created, location: @activity_participant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity/participants/1 or /activity/participants/1.json
  def update
    respond_to do |format|
      if @activity_participant.update(activity_participant_params)
        format.html { redirect_to activity_participant_url(@activity_participant.activity), notice: "Participant was successfully updated." }
        format.json { render :show, status: :ok, location: @activity_participant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity/participants/1 or /activity/participants/1.json
  def destroy
    @activity_participant.destroy
    respond_to do |format|
      format.html { redirect_to activity_participants_url, notice: "Participant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_participant
      @activity_participant = Activity::Participant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_participant_params
      params.fetch(:activity_participant, {}).permit(:participation_type, :contribution, :users_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity/notes_helper.rb
module Activity::NotesHelper
end

app/helpers/activity/participants_helper.rb
module Activity::ParticipantsHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= form.label :name%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :total_cost %>
    <%= form.text_field :total_cost %>
  </div>

  <div class="field">
    <%= form.label :activity_type %>
    <%= form.select(:type_activity, Activity.type_activities.keys.map {|type_activity| [type_activity.titleize,type_activity ]}) %>
  </div>

  <div class="field">
    <%= form.label :initial_date %>
    <%= form.datetime_select :initial_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

<!--  <div class="field">
    <%= form.label :users_id %>
    <%= form.collection_select :users_id, User.order(:id),:id, :username %> <br>
  </div>-->
  



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Activities</h1>

<table class='table'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Total cost</th>
      <th>Activity Type</th>
      <th>Initial date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.id %></td>
        <td><%= activity.name %></td>
        <td><%= activity.description %></td>
        <td><%= activity.location %></td>
        <td><%= activity.total_cost %></td>
        <td><%= activity.type_activity%></td>
        <td><%= activity.initial_date %></td>
        <td><%= activity.end_date %></td>

        
        <td><%= link_to 'Show', activity %></td>

        <% if can? :update, activity %>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <%end%>
        
        
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
        

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %> |
<%= link_to 'Back', home_index_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %> | 
<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Activity name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @activity.location %>
</p>

<p>
  <strong>Total cost:</strong>
  <%= @activity.total_cost %>
</p>

<p>
  <strong>Initial date:</strong>
  <%= @activity.initial_date %>
</p>

<p>
  <strong>Activity type</strong>
  <%= @activity.type_activity %>
</p>

<p>
  <strong>End date:</strong>
  <%= @activity.end_date %>
</p>


<%= link_to 'Back', activities_path %> |
<%= link_to 'Comentarios', activity_notes_url(@activity,@notes) %> |
<%= link_to 'Participantes', activity_participants_url(@activity,@participants) %>